language: node_js
node_js:
  - "7"
install:
  - npm install
script: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  file_glob: true
  file: "dist/"
  on:
    branch: master
